### PR TITLE
chore: migrate wasi-sockets tcp to worker thread

### LINKED ISSUE #315: Migrate current wasi-sockets TCP impl to worker thread
- [x] ✅`preview2_tcp_bind`
- [x] ✅ `preview2_tcp_sockopts`
- [x] ✅ `preview2_tcp_states`
- [x] ✅  `preview2_tcp_connect`
- [ ] ❌ `preview2_tcp_sample_application`

Closes #154

### PR DESCRIPTION
**Pull request by manekinekko**
- [x] ✅`preview2_tcp_bind`
- [ ] ❌  `preview2_tcp_connect`
- [ ] ❌ `preview2_tcp_sample_application`
- [ ] ❌ `preview2_tcp_sockopts`
- [ ] ❌ `preview2_tcp_states`

_* Failing tests are due to missing stream impl_

Closes #315

### CODE REVIEW

**Review by guybedford — APPROVED** [review]
Thanks for starting on this! It would be great to land this with the unit and lint test fixes, then continue to iterate in due course.

**Comment by guybedford** [comment]
Landed in https://github.com/bytecodealliance/jco/commit/823fa9b5e82902c4e5d7b547ba0ae3a3abd296a9.

**Comment by manekinekko** [comment]
Hahaha! Just pushed a commit fixing the lint issue. Will push to another PR :)

**Comment by manekinekko** [comment]
Follow up PR https://github.com/bytecodealliance/jco/pull/319

**Pull request closed without merging**
