### PR TITLE
fix: invalid names in import object

### PR DESCRIPTION
**Pull request by eduardomourar**
~~This prepares the ground for when TypeScript will have support for "Arbitrary module namespace identifier names": https://github.com/microsoft/TypeScript/issues/40594.~~ Instead, we will export an `interface` in replacement of a `namespace`.

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks for the PR, with https://github.com/bytecodealliance/js-component-tools/pull/31 merged there should no longer be update issues if you're able to rebase to the latest main.

**Comment by guybedford** [comment]
This is still failing unfortunately - 

```
Error: test/output/flavorful/flavorful.d.ts(8,25): error TS1005: ';' expected.
Error: test/output/flavorful/flavorful.d.ts(10,3): error TS1109: Expression expected.
Error: test/output/flavorful/flavorful.d.ts(11,1): error TS1128: Declaration or statement expected.
Error: test/output/lists/lists.d.ts(8,16): error TS1003: Identifier expected.
Error: test/output/lists/lists.d.ts(8,25): error TS1005: ';' expected.
Error: test/output/lists/lists.d.ts(10,3): error TS1109: Expression expected.
Error: test/output/lists/lists.d.ts(11,1): error TS1128: Declaration or statement expected.
Error: test/output/many_arguments/many_arguments.d.ts(7,16): error TS1003: Identifier expected.
Error: test/output/many_arguments/many_arguments.d.ts(7,25): error TS1005: ';' expected.
Error: test/output/many_arguments/many_arguments.d.ts(9,3): error TS1109: Expression expected.
Error: test/output/many_arguments/many_arguments.d.ts(10,1): error TS1128: Declaration or statement expected.
Error: test/output/numbers/numbers.d.ts(8,16): error TS1003: Identifier expected.
Error: test/output/numbers/numbers.d.ts(8,25): error TS1005: ';' expected.
Error: test/output/numbers/numbers.d.ts(10,3): error TS1109: Expression expected.
Error: test/output/numbers/numbers.d.ts(11,1): error TS1128: Declaration or statement expected.
Error: test/output/records/records.d.ts(8,16): error TS1003: Identifier expected.
Error: test/output/records/records.d.ts(8,25): error TS1005: ';' expected.
Error: test/output/records/records.d.ts(10,3): error TS1109: Expression expected.
Error: test/output/records/records.d.ts(11,1): error TS1128: Declaration or statement expected.
Error: test/output/strings/strings.d.ts(7,16): error TS1003: Identifier expected.
Error: test/output/strings/strings.d.ts(7,25): error TS1005: ';' expected.
Error: test/output/strings/strings.d.ts(9,3): error TS1109: Expression expected.
Error: test/output/strings/strings.d.ts(10,1): error TS1128: Declaration or statement expected.
Error: test/output/variants/variants.d.ts(8,16): error TS1003: Identifier expected.
Error: test/output/variants/variants.d.ts(8,25): error TS1005: ';' expected.
Error: test/output/variants/variants.d.ts(10,3): error TS1109: Expression expected.
Error: test/output/variants/variants.d.ts(11,1): error TS1128: Declaration or statement expected.
```

**Comment by eduardomourar** [comment]
> This is still failing unfortunately -

The TypeScript compiler might take same time to support this syntax. Should we just generate something like this, instead?

```typescript
import { WasiClocks as WasiClocksImports } from './imports/wasi-clocks';
import { WasiDefaultClocks as WasiDefaultClocksImports } from './imports/wasi-default-clocks';
import { WasiStderr as WasiStderrImports } from './imports/wasi-stderr';
export interface ImportObject {
  "wasi-clocks": typeof WasiClocksImports,
  "wasi-default-clocks": typeof WasiDefaultClocksImports,
  "wasi-stderr": typeof WasiStderrImports,
}
export namespace SomeCommand {
  export function command(stdin: number, stdout: number, args: string[], envVars: [string, string][], preopens: [number, string][]): void;
}

export function instantiate(
compileCore: (path: string, imports: Record<string, any>) => Promise<WebAssembly.Module>,
imports: ImportObject,
instantiateCore?: (module: WebAssembly.Module, imports: Record<string, any>) => Promise<WebAssembly.Instance>
): Promise<typeof Stedi>;
```

**Comment by guybedford** [comment]
Sure, that can work.

**Comment by guybedford** [comment]
Thanks for your work on this!

**Pull request merged**
