### PR TITLE
Toolchain upgrade

### PR DESCRIPTION
**Pull request by guybedford**
Putting up the WIP PR as I work through the latest resource upgrades for the coming release.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@guybedford By "latest resource upgrade" do you mean upgrading to new `.wit` definitions?

**Comment by guybedford** [comment]
@yoshuawuyts yes the latest definitions now use component model resources for streams and polls and file descriptors.

**Comment by guybedford** [comment]
This PR is now complete, pending the HTTP implementation, which I'll be getting to shortly.

Reviews welcome.

**Comment by guybedford** [comment]
I'm going to go ahead and land this for a 0.13 release, to then follow-up with the HTTP preview2 implementation upgrade as a patch on 0.13. This way we can start iterating on the resources WIT already now. I expect it'll only take an extra day to get the HTTP implementation upgraded anyway.

**Pull request merged**
